import {Chess} from '../vendor/chess.js';
import {CHESS_PUZZLES,flight,positionAt,lightColor} from './discovery-data.js';
export function setupDiscovery({pause,resume}){
 const el=document.createElement('dialog');el.id='discovery';el.setAttribute('aria-labelledby','discoveryTitle');el.innerHTML=`<div class="puzzle-header"><span class="eyebrow">MARK'S DISCOVERY CLUB</span><button id="closeDiscovery" aria-label="Return to city">×</button></div><h2 id="discoveryTitle">Try it. Notice it. Explain it.</h2><nav class="discovery-tabs"><button data-lab="flight">Gravity lab</button><button data-lab="light">Light lab</button><button data-lab="chess">Chess table</button></nav><section id="discoveryBody"></section>`;document.body.append(el);const body=el.querySelector('#discoveryBody');let animation=0;
 function stop(){cancelAnimationFrame(animation);}
 function open(mode){pause();show(mode);el.showModal();}
 for(const [label,mode] of [['Science lab','flight'],['Chess table','chess']]){const b=document.createElement('button');b.textContent=label;document.querySelector('.header-links').append(b);b.onclick=()=>open(mode);}
 el.querySelector('#closeDiscovery').onclick=()=>{stop();el.close();resume();};el.addEventListener('cancel',()=>{stop();resume();});el.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>show(b.dataset.lab));
 function show(mode){stop();el.querySelectorAll('[data-lab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lab===mode)));if(mode==='flight')gravity();if(mode==='light')light();if(mode==='chess')chess();}
 function gravity(){body.innerHTML=`<h3>A baseball on Earth… or the Moon?</h3><p>Predict: with the same launch, will the ball fly farther on the Moon?</p><div class="prediction"><button data-predict="farther">Farther</button><button data-predict="shorter">Not as far</button></div><div class="lab-fields"><label>World <select id="gravity"><option value="9.81">Earth · 9.81 m/s²</option><option value="1.62">Moon · 1.62 m/s²</option></select></label><label>Launch angle <input id="angle" type="range" min="15" max="75" value="45" step="5"><output id="angleValue">45°</output></label></div><canvas id="flightPlot" width="700" height="290" aria-label="Baseball trajectory; distance in metres"></canvas><button id="launchBall">Launch ball</button><p id="flightResult" role="status"></p><p class="lab-note">Model: 10 metres per second at launch, level ground, constant gravity, no air resistance. The dashed line shows the other world at the same scale. Real Earth air changes the flight.</p>`;const $=id=>body.querySelector('#'+id);let prediction='';body.querySelectorAll('[data-predict]').forEach(b=>b.onclick=()=>{prediction=b.dataset.predict;body.querySelectorAll('[data-predict]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('flightResult').textContent='Prediction saved. Choose a world and launch!';});
 const draw=(elapsed=0)=>{const g=+$('gravity').value,a=+$('angle').value,p=flight(a,g),ctx=$('flightPlot').getContext('2d'),sx=9,sy=7.5,ox=36,oy=255;ctx.fillStyle='#e9f2ed';ctx.fillRect(0,0,700,290);ctx.strokeStyle='#b7cbc3';ctx.lineWidth=1;ctx.font='12px Arial';ctx.fillStyle='#24344a';for(let x=0;x<=70;x+=10){ctx.beginPath();ctx.moveTo(ox+x*sx,15);ctx.lineTo(ox+x*sx,oy);ctx.stroke();ctx.fillText(x+' m',ox+x*sx-8,278);}ctx.fillText('Height (metres)',10,16);for(let y=0;y<=30;y+=5)ctx.fillText(y,8,oy-y*sy);const path=(grav,color,dash)=>{const f=flight(a,grav);ctx.strokeStyle=color;ctx.setLineDash(dash);ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=100;i++){const pos=positionAt(f.duration*i/100,a,grav);ctx.lineTo(ox+pos.x*sx,oy-pos.y*sy);}ctx.stroke();ctx.setLineDash([]);};path(g===9.81?1.62:9.81,'#8b939f',[6,6]);path(g,'#3a8793',[]);const pos=positionAt(Math.min(elapsed,p.duration),a,g);ctx.beginPath();ctx.arc(ox+pos.x*sx,oy-pos.y*sy,7,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#c64f60';ctx.lineWidth=2;ctx.stroke();};
 function reset(){stop();$('angleValue').textContent=$('angle').value+'°';$('flightResult').textContent='Ready. Compare the two paths, then launch.';draw();}$('angle').oninput=reset;$('gravity').onchange=reset;$('launchBall').onclick=()=>{stop();const g=+$('gravity').value,a=+$('angle').value,p=flight(a,g),start=performance.now();$('flightResult').textContent=`Flight time ${p.duration.toFixed(2)} s · range ${p.range.toFixed(1)} m. ${prediction?(prediction==='farther'?'Your prediction is right! ':'Try comparing the paths: '):''}The Moon’s weaker gravity gives about 6 times the range at this same launch angle.`;const frame=now=>{const t=(now-start)/1000;draw(t);if(t<p.duration)animation=requestAnimationFrame(frame);};animation=requestAnimationFrame(frame);};reset();}
 function light(){body.innerHTML=`<h3>Mix light, not paint.</h3><p>Predict: what do red and green light make together?</p><div class="prediction"><button data-color="yellow">Yellow</button><button data-color="brown">Brown</button></div><div class="light-demo"><div id="mixedLight" aria-label="Result of mixing red, green and blue light"></div><p id="lightReadout" role="status"></p></div><div class="lab-fields">${['Red','Green','Blue'].map((c,i)=>`<label>${c} light <input id="rgb${i}" type="range" min="0" max="255" value="${i===0?255:0}"><output id="rgbValue${i}"></output></label>`).join('')}</div><button id="testYellow">Try red + green</button> <button id="testWhite">Try all three</button><p id="lightAnswer" role="status">Move the sliders and watch the light change.</p><p class="lab-note">A simplified screen model of additive RGB light: red + green = yellow; red + green + blue at full intensity = white. Mixing paint is different because pigments absorb light.</p>`;const $=id=>body.querySelector('#'+id);const update=()=>{const v=[0,1,2].map(i=>+$('rgb'+i).value);$('mixedLight').style.background=lightColor(...v);v.forEach((n,i)=>$('rgbValue'+i).textContent=n);$('lightReadout').textContent=`Red ${v[0]} · Green ${v[1]} · Blue ${v[2]}`;};body.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{body.querySelectorAll('[data-color]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('lightAnswer').textContent='Prediction saved. Try red + green to check.';});[0,1,2].forEach(i=>$('rgb'+i).oninput=update);$('testYellow').onclick=()=>{[255,255,0].forEach((v,i)=>$('rgb'+i).value=v);update();$('lightAnswer').textContent='Yellow! Red and green light add together. This is light, not paint.';};$('testWhite').onclick=()=>{[0,1,2].forEach(i=>$('rgb'+i).value=255);update();$('lightAnswer').textContent='White: all three screen channels are at full intensity.';};update();}
 function chess(){let index=0,selected=null,game;const symbols={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'},names={k:'king',q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn'};body.innerHTML=`<h3 id="chessName"></h3><p>White to move. Checkmate in one move: select a white piece, then a highlighted square.</p><div class="chess-layout"><div id="chessBoard" aria-label="Chess puzzle board"></div><div><p id="chessFeedback" role="status"></p><button id="chessHint">Hint</button><button id="chessReset">Try position again</button><button id="chessNext">Next puzzle →</button><p class="lab-note">Three short puzzles. Try different moves, use a hint and discover why checkmate works. Any legal checkmate is accepted.</p></div></div>`;const $=id=>body.querySelector('#'+id);
 function start(){selected=null;game=new Chess(CHESS_PUZZLES[index].fen);$('chessName').textContent=`${index+1} / 3 · ${CHESS_PUZZLES[index].name}`;$('chessFeedback').textContent='Find a move that leaves the black king no legal escape.';render();}
 function render(){const targets=selected?game.moves({square:selected,verbose:true}).map(m=>m.to):[];$('chessBoard').replaceChildren();for(let rank=8;rank>=1;rank--)for(let file=0;file<8;file++){const square=String.fromCharCode(97+file)+rank,p=game.get(square),b=document.createElement('button');b.className='chess-square '+((file+rank)%2?'light-square':'dark-square')+(selected===square?' selected':'')+(targets.includes(square)?' legal':'');b.setAttribute('aria-label',`${square}${p?' '+(p.color==='w'?'white ':'black ')+names[p.type]:' empty'}`);b.innerHTML=`<span>${p?symbols[p.color+p.type]:''}</span><small>${square}</small>`;b.disabled=game.isCheckmate();b.onclick=()=>{if(p?.color==='w'){selected=square;render();return;}if(!selected){$('chessFeedback').textContent='Choose a white piece first.';return;}const move=game.moves({square:selected,verbose:true}).find(m=>m.to===square);if(!move){$('chessFeedback').textContent='That is not a legal move. Try a highlighted square.';return;}game.move(move);selected=null;if(game.isCheckmate())$('chessFeedback').textContent='Checkmate! '+CHESS_PUZZLES[index].explain;else{game.undo();$('chessFeedback').textContent='Legal move, but Black can still respond. The position is restored — try again.';}render();};$('chessBoard').append(b);}}
 $('chessHint').onclick=()=>$('chessFeedback').textContent=CHESS_PUZZLES[index].hint;$('chessReset').onclick=start;$('chessNext').onclick=()=>{index=(index+1)%CHESS_PUZZLES.length;start();};start();}
}
